version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/code
    depends_on:
      redis:
        condition: service_healthy
    # Add this line to load environment variables from .env
    env_file:
      - .env

  celery:
    build: .
    command: celery -A students worker --loglevel=info
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started
    # Add this line to load environment variables from .env
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A students beat --loglevel=info
    volumes:
      - .:/code
    environment:
      - PYTHONPATH=/code
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started
    # Add this line to load environment variables from .env
    env_file:
      - .env